#==============jdbc配置==============#
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #============== druid 配置==============
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        max-active: 10
      primary: pcmc #应用默认使用数据源
      datasource:
        pcmc:
          url: jdbc:mysql://10.22.50.133:3306/ers?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: root
          password: Sunline!666
  cloud:
    nacos:
      discovery:
        server-addr: 10.22.50.134:8848
        enabled: true
  #==============redis配置==============
  redis:
    host: 10.22.50.134
    password: boss666
    port: 6379
    timeout: 5000
    database: 0

#============== myBatis-Plus配置==============
mybatis-plus:
  mapper-locations: classpath*:com/sunline/modules/**/namesql/*.xml,classpath*:com/sunline/**/mapper/*.xml,classpath*:mybatis/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sunline.api.entity,com.sunline.modules.*.entity
#ribbon的超时时间, 防止feign调用超时
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000