#==============jdbc配置==============#
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #============== druid 配置==============
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        max-active: 10
      primary: pcmc #应用默认使用数据源
      datasource:
        pcmc:
          url: jdbc:mysql://10.22.50.133:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: root
          password: Sunline!666
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.128:8848
        enabled: true
  #==============redis配置==============
  redis:
    host: 192.168.23.128
    password: zzredis
    port: 6379
    timeout: 5000
    database: 0
#mq的配置
rocketmq:
  name-server: 192.168.23.128:9876
  producer:
    group: ${spring.application.name}
    retry-times-when-send-async-failed: 1
  consumer:
    group: ${spring.application.name}