#指定启动端口
server:
  port: 9001

spring:
  profiles:
    active: dev
  #==============应用名配置=============
  application:
    name: boss-bsmc
  main:
    allow-bean-definition-overriding: true
  #==============国际化配置=============
  messages:
    basename: i18n/messages,com.sunline.jraf.messages
  #==============主题模式=============
  jms:
    pub-sub-domain: true

#指定log配置
logging:
  level:
    com.sunline: debug
    org.springframework: warn
  config: classpath:logconf/log4j2.xml

#feign的超时时间, 防止feign调用超时
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 15000 #单位毫秒
        readTimeout: 60000  #单位毫秒
#接入adminLite配置
management:
  endpoints:
    web:
      exposure:
        include: info,env,health,mappings,configprops,metrics
    jmx:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    jolokia:
      enabled: false
sunlog:
  enabled: true          # 是否启用开关，默认 false   es的测试环境密码Sunlinees
  maxCount: 100          # 每次从本地队列读取的最大记录数，默认 100
  redisKey: sunlog_list  # 日志存储到redis中的key，默认 sunlog_list，必须与 admin-server 中配置的 redisKey 保持一致
# 配置文件数据加密
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: sunline