#指定启动端口
server:
  port: 9200
spring:
  profiles:
    active: dev
  #==============应用名配置=============
  application:
    name: product-core
  main:
    allow-bean-definition-overriding: true
#指定log配置
logging:
  level:
    com.platform: debug
    org.springframework: warn

#feign的超时时间, 防止feign调用超时
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 15000 #单位毫秒
        readTimeout: 60000  #单位毫秒
#============== myBatis-Plus配置==============
mybatis-plus:
  mapper-locations: classpath*:com/platform/**/mapper/*.xml,classpath*:mybatis/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.platform.*.entity,com.platform.*.pojo.**