#==============jdbc配置==============#
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #============== druid 配置==============
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        max-active: 10
      primary: pcmc #应用默认使用数据源
      datasource:
        pcmc:
          url: jdbc:mysql://10.22.50.133:3306/z-test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=UTC
          username: root
          password: Sunline!666
  cloud:
    nacos:
      discovery:
        server-addr: 10.22.50.134:8848
        enabled: true
#==============redis配置==============
  redis:
    host: 10.22.50.134
    password: boss666
    port: 6379
    timeout: 5000
    database: 1
  mail:
    host: smtp.qq.com
    protocol: smtp
    username:
    password:
    default-encoding: UTF-8
  smtp:
    auth: true
    starttls:
      enable: true
      required: true
#mq的配置
rocketmq:
  name-server: 192.168.23.129:9876
  producer:
    group: ${spring.application.name}
  consumer:
    group: ${spring.application.name}
#xxl-job的配置
#xxl:
#  job:
#    admin:
#      addresses: http://192.168.23.129:8080/xxl-job-admin
#    accessToken:
#    executor:
#      appname: product-support-executor
#      address:
#      ip:
#      port: 9998
#      ##logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 15